parameters:
    xsolve.cookie_bar.service.class: Xsolve\CookieAcknowledgementBundle\Service\CookieService
    xsolve.cookie_bar.event_listener.class: Xsolve\CookieAcknowledgementBundle\EventListener\CookieBarListener

services:
    xsolve.cookie_bar.service:
        class: %xsolve.cookie_bar.service.class%
        arguments:    ["@templating", %xsolve.cookie_bar.template%]
